project:
  type: website

website:
  title: Byte Busters
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\BB_logo.png
  favicon:  images\BB_logo.png

format:
  html:
    theme: atom-one-dark
    toc: true

execute:
  freeze: auto
