---
title: "Urban Heat Island Detection & Impact Analysis"
subtitle: "Proposal"
format: html
editor: visual
---

## Project Objective

The primary objective of this project is to study and analyze climatological data for three cities inside and outside of the Dallas, TX region, and to classify these cities based on an "Urban Heat Island" (UHI) scale.

In climatology, UHI refers to cities that experience warmer temperatures than nearby rural areas, which occurs when land and natural vegetation are replaced by buildings, pavements, and surfaces that absorb and hold heat. This effect is also known as "micro climate" since a city's infrastructure is creating its own local weather conditions.

By analyzing the micro climate data for Dallas, a major urban city in the country, and two suburban cities outside of Dallas, we can create a classification system for different levels of intensities for UHIs and label these cities accordingly. Additionally, we will perform temporal analysis by comparing and contrasting various weather patterns for different intensities of UHIs.

### Scope and Focus

This project will focus on assessing UHIs in various urban environments, particularly comparing the UHI intensity in the following settings:

1.  [**Dallas (Significant City)**]{.underline}

    Analyzing the UHI in a major metropolitan area with high population density and urbanization. Factors such as pollution, land use, and climate will be considered to determine the UHIs' intensity.

2.  [**Arlington (Suburban Town)**]{.underline}

    Evaluating the UHI in a suburban setting, with a moderate population density and less urban development than a significant city. This comparison will help us understand how UHIs vary in less densely populated areas.

3.  [**Denton (Rural City)**]{.underline}

    Examining the UHI in a rural city, where factors like lower population density, less pollution, and different land use patterns play a role in UHI intensity.

### Dataset Description

The high-level goal of this project is to detect, analyze, and understand **UHIs** by leveraging data mining and machine learning to understand the microclimatic effects of urbanization in various metropolitan landscapes.

Climatological and hourly time-series data has been collected from several weather stations run by the National Weather Service (NWS), Federal Aviation Administration (FAA), and Department of Defense (DOD), which encompass data collected from airports and other significant areas. This data has been divided into three Local Climatological Datasets (LCD) for Arlington, Dallas, and Denton for the year 2022.

The dataset that we've gathered from National Center for Environmental Information (NCEI) (<https://www.ncei.noaa.gov/>) offers these key daily summaries that we will be analyzing:

| Columns                         | Description                                                                                                                                   |
|---------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| DailyAverageDryBulbTemperature  | This is the dry-bulb temperature and is commonly used as the standard air temperature reported. It is given here in whole degrees Fahrenheit. |
| DailyAverageWetBulbTemperature  | This is the wet-bulb temperature. It is given here in whole degrees Fahrenheit.                                                               |
| DailyAverageDewPointTemperature | This is the dew point temperature. It is given here in whole degrees Fahrenheit.                                                              |
| DailyPrecipitation              | Total Liquid Content (TLC) water equivalent amount of precipitation for the day.                                                              |
| DailyAverageSeaLevelPressure    | Sea level pressure given in inches of Mercury (in Hg)                                                                                         |
| DailyAverageStationPressure     | Atmospheric pressure observed at the station during the time of observation. Given in inches of Mercury (in Hg)                               |
| DailyAverageRelativeHumidity    | This is the relative humidity given to the nearest whole percentage.                                                                          |
| DailyAverageWindSpeed           | Speed of the wind at the time of observation given in miles per hour (mph)                                                                    |
| DailySustainedWindDirection     | Wind direction from true north using compass directions (e.g. 360 = true north, 180 = south, 270 = west, etc.)                                |

Additional data is included in the tabulated monthly summaries: maximum, minimum, and average temperatures; deviations from normal; ceiling height; visibility; weather patterns; heating and cooling degree days; fastest wind speeds and their directions; sky cover; and instances of sunshine, snowfall, and snow depth.

## Questions

How do **Urban Heat Islands** vary in intensity across different metropolitan/rural cities in a particular region within a given year and how do we classify different levels of UHI?

\[Time series question\]

## Weekly Plan of Attack (Analysis Plan)

+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| Week No. & Overview                | Individual Weekly Tasks                                                    | Assigned Team Members       | Objective                                                                                     | Deliverables                                                                |
+:==================================:+:==========================================================================:+:===========================:+:=============================================================================================:+=============================================================================+
| [**Week 1\                         | Setting up environment, data blending                                      | *Dhanya, Udit*              | Data cleaning & data pre-processing                                                           | Cleaned dataset ready for exploratory analysis.                             |
| **]{.underline}11/8/23 - 11/15/23  |                                                                            |                             |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
|                                    | Identify missing values and perform imputation to deal with missing values | *Riyanshi, Ajinkya*         | \                                                                                             |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
|                                    | Data type conversions                                                      | *Kendall*                   |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| [**Week 2\                         | Visualization of key metrics                                               | *Udit, Dhanya*              | Gain insights into the dataset and prepare data for model development.                        | A thorough analysis of data insights and prepared features for modeling.    |
| **]{.underline}11/15/23 - 11/22/23 |                                                                            |                             |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| \-                                 | Feature engineering and selection                                          | *Riyanshi*                  | \                                                                                             |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| \-                                 | Data normalization and standardization                                     | *Kendall, Ajinkya*          |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| [**Week 3\                         | Implement Temporal Analysis                                                | *Riyanshi, Kendall, Dhanya* | Identify key time periods of significant UHI intensity                                        | Visualizations of temporal trends in UHI intensity, and actionable insights |
| **]{.underline}11/22/23 - 11/29/23 |                                                                            |                             |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| \-                                 | Analyze trends over the months (seasons)                                   | *Udit, Ajinkya*             | \                                                                                             |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| [**Week 4\                         | Build classification models                                                | *Dhanya, Kendall*           | Develop classification models for classifying UHI intensities and evaluate their performance. | Working models and performance evaluation report.                           |
| **]{.underline}11/29/23 - 12/6/23  |                                                                            |                             |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| \-                                 | Model optimization & cross-validate models                                 | *Riyanshi, Udit*            |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| \-                                 | Evaluation metrics and performance analysis                                | *Ajinkya*                   |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
| [**Week 5 - Presentation\          | Compile project documentation -                                            | \-*Kendall, Dhanya*         | Document the project process and results, and prepare a presentation.                         | Complete project documentation and ready-to-deliver presentation.           |
| **]{.underline}12/6/23- 12/11/23   |                                                                            |                             |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+
|                                    | Prepare final presentation                                                 | *Udit, Riyanshi, Ajinkya*   |                                                                                               |                                                                             |
+------------------------------------+----------------------------------------------------------------------------+-----------------------------+-----------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+

## Organization of the Project Repository

Below are the key folders within the Project repository:

-   **data/**: This directory is designated for essential data files required for the project, including input files.

-   **images/**: This folder serves as the storage location for project-related visual representations and plots.

-   **presentation_files/**: This folder is specifically reserved for materials relevant to project presentations.

-   **\_extra/**: We will brainstorm and store analysis-related content that doesn't directly affect the project workflow.

-   **\_freeze/**: This folder stores the generated files during the build process, preserving the website's specific state at a given moment.

-   **\_site/**: This is where we will generate our static website files after rendering our Quarto documents.

-   **.github/**: This is where we will access and manage GitHub templates and workflow configurations.
